# Generated by Django 5.0 on 2023-12-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0002_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaxCycleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_cycle_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VaxName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VaxProgramName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_program_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VaxCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxcyclename')),
            ],
        ),
        migrations.CreateModel(
            name='Vax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_vax_date', models.DateField(help_text='YYYY-MM-DD', null=True, verbose_name='Vaccination date required')),
                ('vax_date', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Vaccination date')),
                ('symptom_after_vax', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('vaxcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxcycle', verbose_name='Cycle for the vaccine')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxname', verbose_name='Name of the vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='VaxProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.child')),
                ('vax_program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxprogramname')),
            ],
        ),
        migrations.AddField(
            model_name='vaxcycle',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxprogram'),
        ),
    ]
