# Generated by Django 4.2.8 on 2023-12-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0004_alter_child_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
