# Generated by Django 4.2.8 on 2023-12-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0006_remove_vaxcycle_name_remove_vaxcycle_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaxProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_program_name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('Child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.child')),
            ],
        ),
        migrations.CreateModel(
            name='Vax_Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_cycle_name', models.CharField(max_length=64)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Vax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_vax_date', models.DateField(help_text='YYYY-MM-DD', null=True, verbose_name='Vaccination date required')),
                ('vax_date', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Vaccination date')),
                ('symptom_after_vax', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaxname')),
                ('vax_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vax_cycle')),
            ],
        ),
    ]
