# Generated by Django 4.2.8 on 2023-12-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0007_vaxprogram_vax_cycle_vax'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaxprogram',
            name='vax_names',
            field=models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'OPV'), ('HepB', 'HepB'), ('IPV/OPV', 'IPV/OPV'), ('DPTw', 'DPTw'), ('Hib', 'Hib'), ('MMR', 'MMR'), ('TCV', 'TCV'), ('HepA1', 'HepA1')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
