# Generated by Django 4.2.8 on 2023-12-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0008_vaxprogram_vax_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaxprogram',
            name='vax_names',
        ),
        migrations.AddField(
            model_name='vaxprogram',
            name='vaxes',
            field=models.ManyToManyField(to='babyapp.vaxname'),
        ),
    ]
