# Generated by Django 4.2.8 on 2024-01-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0009_remove_vaxprogram_vax_names_vaxprogram_vaxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccine_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_vaccines', models.ManyToManyField(related_name='vaccination_programs', to='babyapp.vaccine_names')),
            ],
        ),
    ]
