# Generated by Django 4.2.8 on 2024-01-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0010_vaccine_names_vaccinationprograms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccinationPrograms',
        ),
    ]
