# Generated by Django 4.2.8 on 2024-01-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0011_delete_vaccinationprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccines', models.ManyToManyField(to='babyapp.vaccine_names')),
            ],
        ),
    ]
