# Generated by Django 4.2.9 on 2024-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0014_hospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='programs_available',
            field=models.ManyToManyField(default=None, to='babyapp.vaccineprograms'),
        ),
    ]
