# Generated by Django 4.2.9 on 2024-01-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0015_alter_hospitals_programs_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
