# Generated by Django 4.2.9 on 2024-01-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0016_delete_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('slots_available', models.IntegerField(blank=True, null=True)),
                ('programs_available', models.ManyToManyField(default=None, to='babyapp.vaccineprograms')),
            ],
        ),
    ]
