# Generated by Django 4.2.9 on 2024-01-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0017_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Taken', 'Taken'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.hospitals')),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.child')),
                ('vaccine_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaccineprograms')),
            ],
        ),
    ]
