# Generated by Django 4.2.9 on 2024-01-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0018_vaccinebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccineBooking',
        ),
    ]
