# Generated by Django 4.2.9 on 2024-01-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('babyapp', '0019_delete_vaccinebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.hospitals')),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaccineprograms')),
            ],
        ),
    ]
