# Generated by Django 4.2.9 on 2024-02-01 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('babyapp', '0021_vaccinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestatus',
            name='parent_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
