# Generated by Django 4.2.9 on 2024-02-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0022_vaccinestatus_parent_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccineStatus',
        ),
    ]
