# Generated by Django 4.2.9 on 2024-02-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0024_vaccinestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccineStatus',
        ),
    ]
