# Generated by Django 4.2.9 on 2024-02-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0025_delete_vaccinestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taken', models.BooleanField(default=False)),
                ('child_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.child')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyapp.vaccineprograms')),
            ],
        ),
    ]
